# Tweet with a video-

vid = {'contributors': None,
       'coordinates': None,
       'created_at': 'Tue Mar 02 17:00:53 +0000 2021',
       'entities': {'hashtags': [],
                    'media': [{'display_url': 'pic.twitter.com/blh1w2PvMv',
                               'expanded_url': 'https://twitter.com/MKBHD/status/1366795657399439365/video/1',
                               'id': 1366795614042935298,
                               'id_str': '1366795614042935298',
                               'indices': [47, 70],
                               'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/1366795614042935298/pu/img/zpDR_Ivv-rEm1gjr.jpg',
                               'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/1366795614042935298/pu/img/zpDR_Ivv-rEm1gjr.jpg',
                               'sizes': {'large': {'h': 1280,
                                                   'resize': 'fit',
                                                   'w': 720},
                                         'medium': {'h': 1200,
                                                    'resize': 'fit',
                                                    'w': 675},
                                         'small': {'h': 680,
                                                   'resize': 'fit',
                                                   'w': 383},
                                         'thumb': {'h': 150,
                                                   'resize': 'crop',
                                                   'w': 150}},
                               'type': 'photo',
                               'url': 'https://t.co/blh1w2PvMv'}],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': [{'id': 1239398544,
                                       'id_str': '1239398544',
                                       'indices': [38, 46],
                                       'name': 'Miguel Lozada',
                                       'screen_name': 'MLozada'}]},
       'extended_entities': {'media': [{'additional_media_info': {'monetizable': False},
                                        'display_url': 'pic.twitter.com/blh1w2PvMv',
                                        'expanded_url': 'https://twitter.com/MKBHD/status/1366795657399439365/video/1',
                                        'id': 1366795614042935298,
                                        'id_str': '1366795614042935298',
                                        'indices': [47, 70],
                                        'media_url': 'http://pbs.twimg.com/ext_tw_video_thumb/1366795614042935298/pu/img/zpDR_Ivv-rEm1gjr.jpg',
                                        'media_url_https': 'https://pbs.twimg.com/ext_tw_video_thumb/1366795614042935298/pu/img/zpDR_Ivv-rEm1gjr.jpg',
                                        'sizes': {'large': {'h': 1280,
                                                            'resize': 'fit',
                                                            'w': 720},
                                                  'medium': {'h': 1200,
                                                             'resize': 'fit',
                                                             'w': 675},
                                                  'small': {'h': 680,
                                                            'resize': 'fit',
                                                            'w': 383},
                                                  'thumb': {'h': 150,
                                                            'resize': 'crop',
                                                            'w': 150}},
                                        'type': 'video',
                                        'url': 'https://t.co/blh1w2PvMv',
                                        'video_info': {'aspect_ratio': [9, 16],
                                                       'duration_millis': 28043,
                                                       'variants': [{'content_type': 'application/x-mpegURL',
                                                                     'url': 'https://video.twimg.com/ext_tw_video/1366795614042935298/pu/pl/_IfgTKhDKPYwygsT.m3u8?tag=10'},
                                                                    {'bitrate': 2176000,
                                                                     'content_type': 'video/mp4',
                                                                     'url': 'https://video.twimg.com/ext_tw_video/1366795614042935298/pu/vid/720x1280/bgTD4eTuzPGYhZYy.mp4?tag=10'},
                                                                    {'bitrate': 832000,
                                                                     'content_type': 'video/mp4',
                                                                     'url': 'https://video.twimg.com/ext_tw_video/1366795614042935298/pu/vid/360x640/RERlWIUIlEbZp1Ey.mp4?tag=10'},
                                                                    {'bitrate': 632000,
                                                                     'content_type': 'video/mp4',
                                                                     'url': 'https://video.twimg.com/ext_tw_video/1366795614042935298/pu/vid/320x568/hetDmnOEhotrzKjW.mp4?tag=10'}]}}]},
       'favorite_count': 15153,
       'favorited': False,
       'geo': None,
       'id': 1366795657399439365,
       'id_str': '1366795657399439365',
       'in_reply_to_screen_name': None,
       'in_reply_to_status_id': None,
       'in_reply_to_status_id_str': None,
       'in_reply_to_user_id': None,
       'in_reply_to_user_id_str': None,
       'is_quote_status': False,
       'lang': 'en',
       'place': None,
       'possibly_sensitive': False,
       'possibly_sensitive_appealable': False,
       'retweet_count': 639,
       'retweeted': False,
       'source': '<a href="http://twitter.com/download/iphone" '
                 'rel="nofollow">Twitter for iPhone</a>',
       'text': 'Useless fact of the day 😅\n'
               'Shoutout to @MLozada https://t.co/blh1w2PvMv',
       'truncated': False,
       'user': {'contributors_enabled': False,
                'created_at': 'Thu Apr 09 00:50:00 +0000 2009',
                'default_profile': False,
                'default_profile_image': False,
                'description': 'Web Video Producer | ⋈ | Pro Ultimate Frisbee '
                               'Player | Host of @WVFRM',
                'entities': {'description': {'urls': []},
                             'url': {'urls': [{'display_url': 'youtube.com/MKBHD',
                                               'expanded_url': 'http://youtube.com/MKBHD',
                                               'indices': [0, 23],
                                               'url': 'https://t.co/zGcF5QxPBI'}]}},
                'favourites_count': 26838,
                'follow_request_sent': None,
                'followers_count': 5023916,
                'following': None,
                'friends_count': 404,
                'geo_enabled': True,
                'has_extended_profile': False,
                'id': 29873662,
                'id_str': '29873662',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 11797,
                'location': 'NYC',
                'name': 'Marques Brownlee',
                'notifications': None,
                'profile_background_color': 'EDECE9',
                'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme15/bg.png',
                'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme15/bg.png',
                'profile_background_tile': True,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/29873662/1614037197',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1364264349204959235/fJPgOBd2_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1364264349204959235/fJPgOBd2_normal.jpg',
                'profile_link_color': '6C4585',
                'profile_sidebar_border_color': '000000',
                'profile_sidebar_fill_color': 'C0DFEC',
                'profile_text_color': '333333',
                'profile_use_background_image': False,
                'protected': False,
                'screen_name': 'MKBHD',
                'statuses_count': 50447,
                'time_zone': None,
                'translator_type': 'regular',
                'url': 'https://t.co/zGcF5QxPBI',
                'utc_offset': None,
                'verified': True}}

# Response with one picture-

pic = {'contributors': None,
       'coordinates': None,
       'created_at': 'Tue Mar 02 18:41:18 +0000 2021',
       'entities': {'hashtags': [],
                    'media': [{'display_url': 'pic.twitter.com/qPJrCFGs8J',
                               'expanded_url': 'https://twitter.com/elonmusk/status/1366820931184717824/photo/1',
                               'id': 1366820929091686402,
                               'id_str': '1366820929091686402',
                               'indices': [30, 53],
                               'media_url': 'http://pbs.twimg.com/media/EvfsZK4UUAISLPc.jpg',
                               'media_url_https': 'https://pbs.twimg.com/media/EvfsZK4UUAISLPc.jpg',
                               'sizes': {'large': {'h': 1094,
                                                   'resize': 'fit',
                                                   'w': 1242},
                                         'medium': {'h': 1057,
                                                    'resize': 'fit',
                                                    'w': 1200},
                                         'small': {'h': 599,
                                                   'resize': 'fit',
                                                   'w': 680},
                                         'thumb': {'h': 150,
                                                   'resize': 'crop',
                                                   'w': 150}},
                               'type': 'photo',
                               'url': 'https://t.co/qPJrCFGs8J'}],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': []},
       'extended_entities': {'media': [{'display_url': 'pic.twitter.com/qPJrCFGs8J',
                                        'expanded_url': 'https://twitter.com/elonmusk/status/1366820931184717824/photo/1',
                                        'id': 1366820929091686402,
                                        'id_str': '1366820929091686402',
                                        'indices': [30, 53],
                                        'media_url': 'http://pbs.twimg.com/media/EvfsZK4UUAISLPc.jpg',
                                        'media_url_https': 'https://pbs.twimg.com/media/EvfsZK4UUAISLPc.jpg',
                                        'sizes': {'large': {'h': 1094,
                                                            'resize': 'fit',
                                                            'w': 1242},
                                                  'medium': {'h': 1057,
                                                             'resize': 'fit',
                                                             'w': 1200},
                                                  'small': {'h': 599,
                                                            'resize': 'fit',
                                                            'w': 680},
                                                  'thumb': {'h': 150,
                                                            'resize': 'crop',
                                                            'w': 150}},
                                        'type': 'photo',
                                        'url': 'https://t.co/qPJrCFGs8J'}]},
       'favorite_count': 141766,
       'favorited': False,
       'geo': None,
       'id': 1366820931184717824,
       'id_str': '1366820931184717824',
       'in_reply_to_screen_name': None,
       'in_reply_to_status_id': None,
       'in_reply_to_status_id_str': None,
       'in_reply_to_user_id': None,
       'in_reply_to_user_id_str': None,
       'is_quote_status': False,
       'lang': 'en',
       'place': None,
       'possibly_sensitive': False,
       'possibly_sensitive_appealable': False,
       'retweet_count': 13076,
       'retweeted': False,
       'source': '<a href="http://twitter.com/download/iphone" '
                 'rel="nofollow">Twitter for iPhone</a>',
       'text': 'Horses are even self-driving! https://t.co/qPJrCFGs8J',
       'truncated': False,
       'user': {'contributors_enabled': False,
                'created_at': 'Tue Jun 02 20:12:29 +0000 2009',
                'default_profile': False,
                'default_profile_image': False,
                'description': '',
                'entities': {'description': {'urls': []}},
                'favourites_count': 8230,
                'follow_request_sent': None,
                'followers_count': 48568805,
                'following': None,
                'friends_count': 103,
                'geo_enabled': False,
                'has_extended_profile': True,
                'id': 44196397,
                'id_str': '44196397',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 65616,
                'location': '',
                'name': 'Elon Musk',
                'notifications': None,
                'profile_background_color': 'C0DEED',
                'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                'profile_background_tile': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/44196397/1576183471',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                'profile_link_color': '0084B4',
                'profile_sidebar_border_color': 'C0DEED',
                'profile_sidebar_fill_color': 'DDEEF6',
                'profile_text_color': '333333',
                'profile_use_background_image': True,
                'protected': False,
                'screen_name': 'elonmusk',
                'statuses_count': 13742,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': True}}

# Response with 4 pics-

pics = {'contributors': None,
        'coordinates': None,
        'created_at': 'Sat Mar 06 06:21:14 +0000 2021',
        'entities': {'hashtags': [],
                     'symbols': [],
                     'urls': [{'display_url': 'twitter.com/i/web/status/1…',
                               'expanded_url': 'https://twitter.com/i/web/status/1368084236582944769',
                               'indices': [117, 140],
                               'url': 'https://t.co/RKGdO9rZPx'}],
                     'user_mentions': []},
        'favorite_count': 464,
        'favorited': False,
        'geo': None,
        'id': 1368084236582944769,
        'id_str': '1368084236582944769',
        'in_reply_to_screen_name': None,
        'in_reply_to_status_id': None,
        'in_reply_to_status_id_str': None,
        'in_reply_to_user_id': None,
        'in_reply_to_user_id_str': None,
        'is_quote_status': False,
        'lang': 'en',
        'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
        'place': None,
        'possibly_sensitive': False,
        'retweet_count': 11,
        'retweeted': False,
        'source': '<a href="http://twitter.com/download/iphone" '
                  'rel="nofollow">Twitter for iPhone</a>',
        'text': 'Today was a good day, finally got to go surfing with friends and '
                'even though the water was painfully bone numbing c… '
                'https://t.co/RKGdO9rZPx',
        'truncated': True,
        'user': {'contributors_enabled': False,
                 'created_at': 'Thu Jan 19 20:38:14 +0000 2012',
                 'default_profile': True,
                 'default_profile_image': False,
                 'description': 'Human | Photographer | Martian',
                 'entities': {'description': {'urls': []},
                              'url': {'urls': [{'display_url': 'linktr.ee/austinbarnard45',
                                                'expanded_url': 'https://linktr.ee/austinbarnard45',
                                                'indices': [0, 23],
                                                'url': 'https://t.co/2IWlSSeXVb'}]}},
                 'favourites_count': 47102,
                 'follow_request_sent': None,
                 'followers_count': 43848,
                 'following': None,
                 'friends_count': 740,
                 'geo_enabled': True,
                 'has_extended_profile': True,
                 'id': 468706269,
                 'id_str': '468706269',
                 'is_translation_enabled': False,
                 'is_translator': False,
                 'lang': None,
                 'listed_count': 475,
                 'location': 'Brownsville, TX',
                 'name': 'Austin Barnard🚀',
                 'notifications': None,
                 'profile_background_color': 'C0DEED',
                 'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                 'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                 'profile_background_tile': False,
                 'profile_banner_url': 'https://pbs.twimg.com/profile_banners/468706269/1590796743',
                 'profile_image_url': 'http://pbs.twimg.com/profile_images/1367605711182716932/_Wfi6m66_normal.jpg',
                 'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1367605711182716932/_Wfi6m66_normal.jpg',
                 'profile_link_color': '1DA1F2',
                 'profile_sidebar_border_color': 'C0DEED',
                 'profile_sidebar_fill_color': 'DDEEF6',
                 'profile_text_color': '333333',
                 'profile_use_background_image': True,
                 'protected': False,
                 'screen_name': 'austinbarnard45',
                 'statuses_count': 7672,
                 'time_zone': None,
                 'translator_type': 'none',
                 'url': 'https://t.co/2IWlSSeXVb',
                 'utc_offset': None,
                 'verified': False}}

# Retweet with truncated text-

retweet = {'contributors': None,
           'coordinates': None,
           'created_at': 'Sat Mar 06 14:37:55 +0000 2021',
           'display_text_range': [0, 140],
           'entities': {'hashtags': [],
                        'symbols': [],
                        'urls': [],
                        'user_mentions': [{'id': 44196397,
                                           'id_str': '44196397',
                                           'indices': [3, 12],
                                           'name': 'Elon Musk',
                                           'screen_name': 'elonmusk'},
                                          {'id': 1686323288,
                                           'id_str': '1686323288',
                                           'indices': [14, 29],
                                           'name': 'Tim Sweeney',
                                           'screen_name': 'TimSweeneyEpic'}]},
           'favorite_count': 0,
           'favorited': False,
           'full_text': 'RT @elonmusk: @TimSweeneyEpic Thrust was low despite being '
                        'commanded high for reasons unknown at present, hence hard '
                        'touchdown. We’ve never…',
           'geo': None,
           'id': 1368209230931628037,
           'id_str': '1368209230931628037',
           'in_reply_to_screen_name': None,
           'in_reply_to_status_id': None,
           'in_reply_to_status_id_str': None,
           'in_reply_to_user_id': None,
           'in_reply_to_user_id_str': None,
           'is_quote_status': False,
           'lang': 'en',
           'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
           'place': None,
           'retweet_count': 680,
           'retweeted': False,
           'retweeted_status': {'contributors': None,
                                'coordinates': None,
                                'created_at': 'Sat Mar 06 01:51:37 +0000 2021',
                                'display_text_range': [16, 250],
                                'entities': {'hashtags': [],
                                             'symbols': [],
                                             'urls': [],
                                             'user_mentions': [{'id': 1686323288,
                                                                'id_str': '1686323288',
                                                                'indices': [0, 15],
                                                                'name': 'Tim Sweeney',
                                                                'screen_name': 'TimSweeneyEpic'}]},
                                'favorite_count': 8645,
                                'favorited': False,
                                'full_text': '@TimSweeneyEpic Thrust was low despite '
                                             'being commanded high for reasons unknown '
                                             'at present, hence hard touchdown. We’ve '
                                             'never seen this before.\n'
                                             '\n'
                                             'Next time, min two engines all the way to '
                                             'the ground &amp; restart engine 3 if '
                                             'engine 1 or 2 have issues.',
                                'geo': None,
                                'id': 1368016384458858500,
                                'id_str': '1368016384458858500',
                                'in_reply_to_screen_name': 'elonmusk',
                                'in_reply_to_status_id': 1368014448426807296,
                                'in_reply_to_status_id_str': '1368014448426807296',
                                'in_reply_to_user_id': 44196397,
                                'in_reply_to_user_id_str': '44196397',
                                'is_quote_status': False,
                                'lang': 'en',
                                'metadata': {'iso_language_code': 'en',
                                             'result_type': 'recent'},
                                'place': None,
                                'retweet_count': 680,
                                'retweeted': False,
                                'source': '<a href="http://twitter.com/download/iphone" '
                                          'rel="nofollow">Twitter for iPhone</a>',
                                'truncated': False,
                                'user': {'contributors_enabled': False,
                                         'created_at': 'Tue Jun 02 20:12:29 +0000 2009',
                                         'default_profile': False,
                                         'default_profile_image': False,
                                         'description': '',
                                         'entities': {'description': {'urls': []}},
                                         'favourites_count': 8231,
                                         'follow_request_sent': None,
                                         'followers_count': 48585036,
                                         'following': None,
                                         'friends_count': 103,
                                         'geo_enabled': False,
                                         'has_extended_profile': True,
                                         'id': 44196397,
                                         'id_str': '44196397',
                                         'is_translation_enabled': False,
                                         'is_translator': False,
                                         'lang': None,
                                         'listed_count': 65657,
                                         'location': '',
                                         'name': 'Elon Musk',
                                         'notifications': None,
                                         'profile_background_color': 'C0DEED',
                                         'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                                         'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                                         'profile_background_tile': False,
                                         'profile_banner_url': 'https://pbs.twimg.com/profile_banners/44196397/1576183471',
                                         'profile_image_url': 'http://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                                         'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                                         'profile_link_color': '0084B4',
                                         'profile_sidebar_border_color': 'C0DEED',
                                         'profile_sidebar_fill_color': 'DDEEF6',
                                         'profile_text_color': '333333',
                                         'profile_use_background_image': True,
                                         'protected': False,
                                         'screen_name': 'elonmusk',
                                         'statuses_count': 13743,
                                         'time_zone': None,
                                         'translator_type': 'none',
                                         'url': None,
                                         'utc_offset': None,
                                         'verified': True}},
           'source': '<a href="http://twitter.com/download/iphone" '
                     'rel="nofollow">Twitter for iPhone</a>',
           'truncated': False,
           'user': {'contributors_enabled': False,
                    'created_at': 'Thu Jan 19 20:38:14 +0000 2012',
                    'default_profile': True,
                    'default_profile_image': False,
                    'description': 'Human | Photographer | Martian',
                    'entities': {'description': {'urls': []},
                                 'url': {'urls': [{'display_url': 'linktr.ee/austinbarnard45',
                                                   'expanded_url': 'https://linktr.ee/austinbarnard45',
                                                   'indices': [0, 23],
                                                   'url': 'https://t.co/2IWlSSeXVb'}]}},
                    'favourites_count': 47098,
                    'follow_request_sent': None,
                    'followers_count': 43847,
                    'following': None,
                    'friends_count': 740,
                    'geo_enabled': True,
                    'has_extended_profile': True,
                    'id': 468706269,
                    'id_str': '468706269',
                    'is_translation_enabled': False,
                    'is_translator': False,
                    'lang': None,
                    'listed_count': 474,
                    'location': 'Brownsville, TX',
                    'name': 'Austin Barnard🚀',
                    'notifications': None,
                    'profile_background_color': 'C0DEED',
                    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    'profile_background_tile': False,
                    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/468706269/1590796743',
                    'profile_image_url': 'http://pbs.twimg.com/profile_images/1367605711182716932/_Wfi6m66_normal.jpg',
                    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1367605711182716932/_Wfi6m66_normal.jpg',
                    'profile_link_color': '1DA1F2',
                    'profile_sidebar_border_color': 'C0DEED',
                    'profile_sidebar_fill_color': 'DDEEF6',
                    'profile_text_color': '333333',
                    'profile_use_background_image': True,
                    'protected': False,
                    'screen_name': 'austinbarnard45',
                    'statuses_count': 7671,
                    'time_zone': None,
                    'translator_type': 'none',
                    'url': 'https://t.co/2IWlSSeXVb',
                    'utc_offset': None,
                    'verified': False}}

# Gif with caption-

gif = {'contributors': None,
       'coordinates': None,
       'created_at': 'Mon Mar 01 19:49:24 +0000 2021',
       'display_text_range': [12, 49],
       'entities': {'hashtags': [],
                    'media': [{'display_url': 'pic.twitter.com/QdOAAGnuE8',
                               'expanded_url': 'https://twitter.com/FulyMe/status/1366475680951672832/photo/1',
                               'id': 1366475674064547841,
                               'id_str': '1366475674064547841',
                               'indices': [50, 73],
                               'media_url': 'http://pbs.twimg.com/tweet_video_thumb/EvayYrrUcAEaJK_.jpg',
                               'media_url_https': 'https://pbs.twimg.com/tweet_video_thumb/EvayYrrUcAEaJK_.jpg',
                               'sizes': {'large': {'h': 206,
                                                   'resize': 'fit',
                                                   'w': 500},
                                         'medium': {'h': 206,
                                                    'resize': 'fit',
                                                    'w': 500},
                                         'small': {'h': 206,
                                                   'resize': 'fit',
                                                   'w': 500},
                                         'thumb': {'h': 150,
                                                   'resize': 'crop',
                                                   'w': 150}},
                               'type': 'photo',
                               'url': 'https://t.co/QdOAAGnuE8'}],
                    'symbols': [],
                    'urls': [],
                    'user_mentions': [{'id': 2907774137,
                                       'id_str': '2907774137',
                                       'indices': [0, 11],
                                       'name': 'Archillect',
                                       'screen_name': 'archillect'}]},
       'extended_entities': {'media': [{'display_url': 'pic.twitter.com/QdOAAGnuE8',
                                        'expanded_url': 'https://twitter.com/FulyMe/status/1366475680951672832/photo/1',
                                        'id': 1366475674064547841,
                                        'id_str': '1366475674064547841',
                                        'indices': [50, 73],
                                        'media_url': 'http://pbs.twimg.com/tweet_video_thumb/EvayYrrUcAEaJK_.jpg',
                                        'media_url_https': 'https://pbs.twimg.com/tweet_video_thumb/EvayYrrUcAEaJK_.jpg',
                                        'sizes': {'large': {'h': 206,
                                                            'resize': 'fit',
                                                            'w': 500},
                                                  'medium': {'h': 206,
                                                             'resize': 'fit',
                                                             'w': 500},
                                                  'small': {'h': 206,
                                                            'resize': 'fit',
                                                            'w': 500},
                                                  'thumb': {'h': 150,
                                                            'resize': 'crop',
                                                            'w': 150}},
                                        'type': 'animated_gif',
                                        'url': 'https://t.co/QdOAAGnuE8',
                                        'video_info': {'aspect_ratio': [250, 103],
                                                       'variants': [{'bitrate': 0,
                                                                     'content_type': 'video/mp4',
                                                                     'url': 'https://video.twimg.com/tweet_video/EvayYrrUcAEaJK_.mp4'}]}}]},
       'favorite_count': 7,
       'favorited': False,
       'full_text': '@archillect 🖤 I do enjoy watching... long movies. '
                    'https://t.co/QdOAAGnuE8',
       'geo': None,
       'id': 1366475680951672832,
       'id_str': '1366475680951672832',
       'in_reply_to_screen_name': 'archillect',
       'in_reply_to_status_id': 1366471751908134922,
       'in_reply_to_status_id_str': '1366471751908134922',
       'in_reply_to_user_id': 2907774137,
       'in_reply_to_user_id_str': '2907774137',
       'is_quote_status': False,
       'lang': 'en',
       'metadata': {'iso_language_code': 'en', 'result_type': 'recent'},
       'place': None,
       'possibly_sensitive': False,
       'retweet_count': 0,
       'retweeted': False,
       'source': '<a href="http://twitter.com/download/android" '
                 'rel="nofollow">Twitter for Android</a>',
       'truncated': False,
       'user': {'contributors_enabled': False,
                'created_at': 'Sun Jan 10 23:54:33 +0000 2021',
                'default_profile': True,
                'default_profile_image': False,
                'description': 'Daydreaming since day one...',
                'entities': {'description': {'urls': []}},
                'favourites_count': 8638,
                'follow_request_sent': None,
                'followers_count': 6,
                'following': None,
                'friends_count': 138,
                'geo_enabled': False,
                'has_extended_profile': True,
                'id': 1348417454364495873,
                'id_str': '1348417454364495873',
                'is_translation_enabled': False,
                'is_translator': False,
                'lang': None,
                'listed_count': 0,
                'location': 'California, USA',
                'name': 'Wonder°fuly°Me',
                'notifications': None,
                'profile_background_color': 'F5F8FA',
                'profile_background_image_url': None,
                'profile_background_image_url_https': None,
                'profile_background_tile': False,
                'profile_banner_url': 'https://pbs.twimg.com/profile_banners/1348417454364495873/1612518124',
                'profile_image_url': 'http://pbs.twimg.com/profile_images/1348419230522216449/ZTJ_0ADa_normal.jpg',
                'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1348419230522216449/ZTJ_0ADa_normal.jpg',
                'profile_link_color': '1DA1F2',
                'profile_sidebar_border_color': 'C0DEED',
                'profile_sidebar_fill_color': 'DDEEF6',
                'profile_text_color': '333333',
                'profile_use_background_image': True,
                'protected': False,
                'screen_name': 'FulyMe',
                'statuses_count': 377,
                'time_zone': None,
                'translator_type': 'none',
                'url': None,
                'utc_offset': None,
                'verified': False}}

# Tweet in reply to another-
replied = {'contributors': None,
           'coordinates': None,
           'created_at': 'Sat Mar 06 23:35:31 +0000 2021',
           'display_text_range': [13, 126],
           'entities': {'hashtags': [],
                        'symbols': [],
                        'urls': [],
                        'user_mentions': [{'id': 1161703589942878208,
                                           'id_str': '1161703589942878208',
                                           'indices': [0, 12],
                                           'name': 'Gary Black',
                                           'screen_name': 'garyblack00'}]},
           'favorite_count': 7656,
           'favorited': False,
           'full_text': '@garyblack00 Update probably in Q2. Cybertruck will be built at '
                        'Giga Texas, so focus right now is on getting that beast built.',
           'geo': None,
           'id': 1368344522413903872,
           'id_str': '1368344522413903872',
           'in_reply_to_screen_name': 'garyblack00',
           'in_reply_to_status_id': 1368337974501535756,
           'in_reply_to_status_id_str': '1368337974501535756',
           'in_reply_to_user_id': 1161703589942878208,
           'in_reply_to_user_id_str': '1161703589942878208',
           'is_quote_status': False,
           'lang': 'en',
           'metadata': {'iso_language_code': 'en', 'result_type': 'popular'},
           'place': None,
           'retweet_count': 674,
           'retweeted': False,
           'source': '<a href="http://twitter.com/download/iphone" '
                     'rel="nofollow">Twitter for iPhone</a>',
           'truncated': False,
           'user': {'contributors_enabled': False,
                    'created_at': 'Tue Jun 02 20:12:29 +0000 2009',
                    'default_profile': False,
                    'default_profile_image': False,
                    'description': '',
                    'entities': {'description': {'urls': []}},
                    'favourites_count': 8233,
                    'follow_request_sent': None,
                    'followers_count': 48644924,
                    'following': None,
                    'friends_count': 103,
                    'geo_enabled': False,
                    'has_extended_profile': True,
                    'id': 44196397,
                    'id_str': '44196397',
                    'is_translation_enabled': False,
                    'is_translator': False,
                    'lang': None,
                    'listed_count': 65652,
                    'location': '',
                    'name': 'Elon Musk',
                    'notifications': None,
                    'profile_background_color': 'C0DEED',
                    'profile_background_image_url': 'http://abs.twimg.com/images/themes/theme1/bg.png',
                    'profile_background_image_url_https': 'https://abs.twimg.com/images/themes/theme1/bg.png',
                    'profile_background_tile': False,
                    'profile_banner_url': 'https://pbs.twimg.com/profile_banners/44196397/1576183471',
                    'profile_image_url': 'http://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                    'profile_image_url_https': 'https://pbs.twimg.com/profile_images/1364491704817098753/V22-Luf7_normal.jpg',
                    'profile_link_color': '0084B4',
                    'profile_sidebar_border_color': 'C0DEED',
                    'profile_sidebar_fill_color': 'DDEEF6',
                    'profile_text_color': '333333',
                    'profile_use_background_image': True,
                    'protected': False,
                    'screen_name': 'elonmusk',
                    'statuses_count': 13749,
                    'time_zone': None,
                    'translator_type': 'none',
                    'url': None,
                    'utc_offset': None,
                    'verified': True}}
